development:
  adapter: solid_cable

test:
  adapter: test

production:
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: binome_app_production
  adapter: solid_cable
